name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{ matrix.otp }}

    strategy:
      fail-fast: false
      matrix:
        otp: ["26.0", "25.3", "24.3"]
        os: ["ubuntu-22.04"]
        include:
          - otp: "23.3"
            os: "ubuntu-20.04"
          - otp: "22.3"
            os: "ubuntu-20.04"
          - otp: "21.3"
            os: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: make

      - name: xref
        run: make xref
        if: ${{ matrix.otp != '23.3' }}

      - name: Code formatter validation
        run: make format_check

      - name: Eunit test
        run: make eunit

      - name: Proper test
        run: make proper

      - name: Check coverage
        run: make cover

      - name: Generate docs
        run: make doc

      - name: Dialyze
        run: make dialyzer
