name: Hot upgrade
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Hot code upgrade from ${{ matrix.from_version }} on OTP-${{ matrix.otp }}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-20.04"]
        otp: ["23.3"]
        rebar3: ["3.17.0"]
        from_version:
            - "1.5.2"
            - "9c28fb479f9329e2a1644565a632bc222780f1b7"

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}

      - name: Hot-upgrade
        run: make hotupgrade_setup BASE_REV=${{ matrix.from_version }} hotupgrade_check
